import Link from "next/link";

const lessons=[
 {term:"Option",technical:"A contract that gives you a right, but not a requirement, to buy or sell something later at a fixed price.",kid:"It is like paying for a special coupon. You can use it if the coupon helps, or throw it away if it does not."},
 {term:"Call option",technical:"The right to buy the underlying asset at the strike price before or at expiration, depending on the contract style.",kid:"You get a ticket that says: ‘I may buy the toy for $100 later, even if everyone else wants $120.’"},
 {term:"Premium",technical:"The price paid for the option contract. One listed equity option usually represents 100 shares.",kid:"It is the price of the magic ticket. The ticket is not free."},
 {term:"Strike price",technical:"The fixed exercise price written into the contract.",kid:"It is the price printed on your coupon. It stays the same while the world price moves around it."},
 {term:"Bid / ask / spread",technical:"Bid is the highest displayed buying price; ask is the lowest displayed selling price; spread is ask minus bid.",kid:"One person says ‘I will pay $9.’ Another says ‘I need $10.’ The $1 difference is the hallway between them."},
 {term:"Delta",technical:"The first-order sensitivity of option value to a one-unit move in the underlying; call delta is between 0 and 1 in the simple case.",kid:"If the stock takes one small step, delta guesses how many tiny steps the option takes."},
 {term:"Gamma",technical:"The rate at which delta changes as the underlying moves. High gamma means the option’s response can bend quickly.",kid:"Delta is the steering wheel angle; gamma tells you how quickly the steering wheel itself turns."},
 {term:"Theta",technical:"The sensitivity of option value to the passage of time, usually negative for a long call with other inputs fixed.",kid:"The option is an ice cube. Each day, a little of its time melts away."},
 {term:"Vega / volatility",technical:"Vega measures sensitivity to implied volatility; volatility describes the market’s expected size of future movement, not direction.",kid:"More wobble means more chance of a big surprise. A choice is more useful when surprises may be large."},
 {term:"Market order",technical:"An instruction to trade immediately against available liquidity, accepting the current price and possible slippage.",kid:"You shout ‘I want it now!’ You get it quickly, but you may pay the nearest price instead of your favorite price."},
 {term:"Limit order",technical:"An instruction to trade only at a specified price or better; it may never fill.",kid:"You say ‘I will buy only if the lemonade costs $1.’ You might save money, but the stand may sell out first."},
 {term:"Mark-to-market P&L",technical:"The change in account value after revaluing open positions at the current market estimate; unrealized does not mean imaginary, but it is not locked in until closed.",kid:"We look at what your toys could sell for today. The number can change before you actually sell them."},
 {term:"Liquidity / slippage",technical:"Liquidity is how much can trade near the displayed price. Slippage is the difference between the expected and executed price, often caused by urgency or a thin book.",kid:"A deep box has lots of toys at the same price. An almost-empty box makes you pay a different price for the next toy."},
 {term:"Implied volatility",technical:"The volatility input backed out of an option’s market price; it is a price of uncertainty, not a guaranteed forecast.",kid:"It is the crowd’s guess about how bouncy the ball might be, measured by what they pay for the ticket."}
];
export default function LearnPage(){return <main><aside><div className="brand"><div className="mark">∑</div><div><strong>FILTRATION</strong><small>𝓕ₜ / RESEARCH LAB</small></div></div><nav><Link href="/" className="nav-link">← Research Overview</Link><Link href="/arena" className="nav-link">02 / Trading Arena</Link><div className="nav-current">10 / EXPLAIN IT SIMPLY</div></nav><div className="sidebar-bottom"><div className="status"><span className="dot"/>LEARNING MODE ONLINE</div><p>Technical precision<br/>Plain-language explanations</p></div></aside><section className="workspace"><header><div><p className="eyebrow">MARKET VOCABULARY / TWO LENSES</p><h1>Explain It Like I’m Five</h1></div><div className="header-actions"><span className="chip"><span className="dot"/>LEARN · THEN TEST</span><div className="avatar">QT</div></div></header><div className="tribunal-hero panel"><div><p className="eyebrow">THE PROMISE</p><h2>Big words become small pictures.</h2><p>Read the technical definition first, then the tiny story. The story is a learning bridge—not a replacement for the math, contract, or risk disclosure.</p></div><div className="verdict-score"><strong>14</strong><span>core terms</span></div></div><div className="lesson-grid">{lessons.map(x=><article className="panel lesson" key={x.term}><div className="panel-head"><span>{x.term}</span><em>TECHNICAL → SIMPLE</em></div><div className="lesson-body"><p><b>Technical:</b> {x.technical}</p><p className="simple"><b>Like you’re five:</b> {x.kid}</p></div></article>)}</div><div className="panel lesson-footer"><p><b>Important:</b> Options can lose all of their premium, and leveraged positions can lose more than a beginner expects. Use the sandbox first; it uses pretend cash and sends no orders.</p><Link href="/arena" className="primary">Practice in the demo arena →</Link></div></section></main>}
