import Link from "next/link";

const sections=[
  ["Quantitative engine","Black–Scholes, Greeks, seeded GBM under P/Q measures, Monte Carlo intervals, put-call parity, and a discounted-underlying martingale diagnostic."],
  ["Execution model","A deterministic price-time exchange with latency, cancellation, partial fills, fees, tick size, position limits, and accounting reconciliation."],
  ["Research protocol","Common seeds, explicit costs, stress environments, 60/20/20 untouched selection, family-wide bootstrap diagnostics, and decision replay."],
  ["Honest scope","All results are synthetic. No live data, historical performance, brokerage routing, or profitability claim is present."],
];
export default function MethodologyPage(){return <main><aside><div className="brand"><div className="mark">∑</div><div><strong>PROJECT TBD</strong><small>QUANT LAB / 0.1</small></div></div><nav><Link href="/" className="nav-link">← Pricing Laboratory</Link><div className="nav-current">09 / METHODOLOGY</div><Link href="/tribunal" className="nav-link">→ Strategy Tribunal</Link></nav><div className="sidebar-bottom"><div className="status"><span className="dot"/>DOCUMENTATION ONLINE</div><p>Reproducible protocol<br/>Synthetic data only</p></div></aside><section className="workspace"><header><div><p className="eyebrow">METHOD / REPRODUCIBILITY / LIMITATIONS</p><h1>Methodology</h1></div><div className="header-actions"><span className="chip"><span className="dot"/>EXPERIMENTAL</span><div className="avatar">QT</div></div></header><div className="tribunal-hero panel"><div><p className="eyebrow">RESEARCH QUESTION</p><h2>When does a market-making decision remain rational after model error, latency, adverse selection, inventory risk, and costs?</h2><p>The lab is designed to make every assumption inspectable, every result seeded, and every performance statement appropriately bounded.</p></div></div><section className="panel methodology-grid">{sections.map(([title,body],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{body}</p></article>)}</section><section className="panel strategy-detail"><div className="panel-head"><span>START HERE</span><em>WORKFLOW</em></div><div className="detail-grid"><div><h3>Price → Execute → Stress → Validate → Audit</h3><p>Use the sidebar to move from analytic pricing into the exchange arena, compare policies, inspect declared stress regimes, review untouched selection, and finish at the Tribunal.</p></div><div className="scope-box"><b>PRIMARY ARTIFACTS</b><span><Link href="/strategy" className="nav-link-inline">Strategy Lab</Link> · <Link href="/stress" className="nav-link-inline">Stress Lab</Link> · <Link href="/validation" className="nav-link-inline">Validation</Link> · <Link href="/inference" className="nav-link-inline">Inference</Link></span></div></div></section><p className="footnote"><span>DOCS · docs/EXPERIMENT_PROTOCOL.md</span><span>STATUS · <b className="ok">DISCLOSED</b></span><span>NO LIVE CLAIM</span></p></section></main>}
